# Generated by Django 4.2.1 on 2023-11-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-time_create'], name='app_game_time_cr_7fb782_idx'),
        ),
    ]
