# Generated by Django 4.2.1 on 2023-11-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_game_slug_game_app_game_time_cr_7fb782_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
