# Generated by Django 4.2.1 on 2023-11-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_game_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
