# Generated by Django 4.2.1 on 2023-11-19 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category_game_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.category'),
        ),
    ]
