# Generated by Django 4.2.1 on 2023-12-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tagpost_game_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-time_create'], 'verbose_name': 'Игры', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='tagpost',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
    ]
